/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TeamId = IDL.Nat;
export const TournamentId = IDL.Nat;
export const AddPlayerInput = IDL.Record({
  'name' : IDL.Text,
  'number' : IDL.Nat,
  'teamId' : TeamId,
  'position' : IDL.Text,
  'tournamentId' : TournamentId,
});
export const PlayerId = IDL.Nat;
export const PlayerView = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'number' : IDL.Nat,
  'teamId' : TeamId,
  'position' : IDL.Text,
  'tournamentId' : TournamentId,
});
export const AddTeamInput = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'tournamentId' : TournamentId,
});
export const TeamView = IDL.Record({
  'id' : TeamId,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'tournamentId' : TournamentId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchId = IDL.Nat;
export const TournamentFormat = IDL.Variant({
  'knockout' : IDL.Null,
  'hybrid' : IDL.Null,
  'league' : IDL.Null,
});
export const CreateTournamentInput = IDL.Record({
  'totalTeams' : IDL.Nat,
  'name' : IDL.Text,
  'format' : TournamentFormat,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const TournamentView = IDL.Record({
  'id' : TournamentId,
  'status' : TournamentStatus,
  'totalTeams' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'format' : TournamentFormat,
});
export const EditPlayerInput = IDL.Record({
  'playerId' : PlayerId,
  'name' : IDL.Text,
  'number' : IDL.Nat,
  'position' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const MatchPhase = IDL.Variant({
  'knockoutRound' : IDL.Nat,
  'leagueStage' : IDL.Null,
});
export const MatchView = IDL.Record({
  'id' : MatchId,
  'status' : MatchStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'awayTeamId' : TeamId,
  'homeTeamId' : TeamId,
  'homeScore' : IDL.Nat,
  'awayScore' : IDL.Nat,
  'phase' : MatchPhase,
  'tournamentId' : TournamentId,
  'scheduledAt' : Timestamp,
});
export const KnockoutBracketMatch = IDL.Record({
  'winnerId' : IDL.Opt(TeamId),
  'awayTeamId' : IDL.Opt(TeamId),
  'homeTeamId' : IDL.Opt(TeamId),
  'matchId' : IDL.Opt(MatchId),
  'round' : IDL.Nat,
});
export const LeagueStandingRow = IDL.Record({
  'won' : IDL.Nat,
  'teamName' : IDL.Text,
  'goalDifference' : IDL.Int,
  'played' : IDL.Nat,
  'lost' : IDL.Nat,
  'goalsFor' : IDL.Nat,
  'goalsAgainst' : IDL.Nat,
  'teamId' : TeamId,
  'position' : IDL.Nat,
  'drawn' : IDL.Nat,
  'points' : IDL.Nat,
});
export const UpdateScoreInput = IDL.Record({
  'matchId' : MatchId,
  'homeScore' : IDL.Nat,
  'awayScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addPlayer' : IDL.Func([AddPlayerInput], [PlayerView], []),
  'addTeam' : IDL.Func([AddTeamInput], [TeamView], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeMatch' : IDL.Func([MatchId], [], []),
  'createTournament' : IDL.Func([CreateTournamentInput], [TournamentView], []),
  'editPlayer' : IDL.Func([EditPlayerInput], [], []),
  'generateFixtures' : IDL.Func([TournamentId], [IDL.Vec(MatchView)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKnockoutBracket' : IDL.Func(
      [TournamentId],
      [IDL.Vec(KnockoutBracketMatch)],
      ['query'],
    ),
  'getLeagueStandings' : IDL.Func(
      [TournamentId],
      [IDL.Vec(LeagueStandingRow)],
      ['query'],
    ),
  'getMatchesByTournament' : IDL.Func(
      [TournamentId],
      [IDL.Vec(MatchView)],
      ['query'],
    ),
  'getPlayersByTeam' : IDL.Func([TeamId], [IDL.Vec(PlayerView)], ['query']),
  'getPlayersByTournament' : IDL.Func(
      [TournamentId],
      [IDL.Vec(PlayerView)],
      ['query'],
    ),
  'getRecentResults' : IDL.Func(
      [TournamentId, IDL.Nat],
      [IDL.Vec(MatchView)],
      ['query'],
    ),
  'getTeamsByTournament' : IDL.Func(
      [TournamentId],
      [IDL.Vec(TeamView)],
      ['query'],
    ),
  'getTournament' : IDL.Func(
      [TournamentId],
      [IDL.Opt(TournamentView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTournaments' : IDL.Func([], [IDL.Vec(TournamentView)], ['query']),
  'updateScore' : IDL.Func([UpdateScoreInput], [], []),
  'updateTournamentStatus' : IDL.Func([TournamentId, TournamentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TeamId = IDL.Nat;
  const TournamentId = IDL.Nat;
  const AddPlayerInput = IDL.Record({
    'name' : IDL.Text,
    'number' : IDL.Nat,
    'teamId' : TeamId,
    'position' : IDL.Text,
    'tournamentId' : TournamentId,
  });
  const PlayerId = IDL.Nat;
  const PlayerView = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'number' : IDL.Nat,
    'teamId' : TeamId,
    'position' : IDL.Text,
    'tournamentId' : TournamentId,
  });
  const AddTeamInput = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'tournamentId' : TournamentId,
  });
  const TeamView = IDL.Record({
    'id' : TeamId,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'tournamentId' : TournamentId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchId = IDL.Nat;
  const TournamentFormat = IDL.Variant({
    'knockout' : IDL.Null,
    'hybrid' : IDL.Null,
    'league' : IDL.Null,
  });
  const CreateTournamentInput = IDL.Record({
    'totalTeams' : IDL.Nat,
    'name' : IDL.Text,
    'format' : TournamentFormat,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const TournamentView = IDL.Record({
    'id' : TournamentId,
    'status' : TournamentStatus,
    'totalTeams' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'format' : TournamentFormat,
  });
  const EditPlayerInput = IDL.Record({
    'playerId' : PlayerId,
    'name' : IDL.Text,
    'number' : IDL.Nat,
    'position' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const MatchPhase = IDL.Variant({
    'knockoutRound' : IDL.Nat,
    'leagueStage' : IDL.Null,
  });
  const MatchView = IDL.Record({
    'id' : MatchId,
    'status' : MatchStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'awayTeamId' : TeamId,
    'homeTeamId' : TeamId,
    'homeScore' : IDL.Nat,
    'awayScore' : IDL.Nat,
    'phase' : MatchPhase,
    'tournamentId' : TournamentId,
    'scheduledAt' : Timestamp,
  });
  const KnockoutBracketMatch = IDL.Record({
    'winnerId' : IDL.Opt(TeamId),
    'awayTeamId' : IDL.Opt(TeamId),
    'homeTeamId' : IDL.Opt(TeamId),
    'matchId' : IDL.Opt(MatchId),
    'round' : IDL.Nat,
  });
  const LeagueStandingRow = IDL.Record({
    'won' : IDL.Nat,
    'teamName' : IDL.Text,
    'goalDifference' : IDL.Int,
    'played' : IDL.Nat,
    'lost' : IDL.Nat,
    'goalsFor' : IDL.Nat,
    'goalsAgainst' : IDL.Nat,
    'teamId' : TeamId,
    'position' : IDL.Nat,
    'drawn' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const UpdateScoreInput = IDL.Record({
    'matchId' : MatchId,
    'homeScore' : IDL.Nat,
    'awayScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addPlayer' : IDL.Func([AddPlayerInput], [PlayerView], []),
    'addTeam' : IDL.Func([AddTeamInput], [TeamView], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeMatch' : IDL.Func([MatchId], [], []),
    'createTournament' : IDL.Func(
        [CreateTournamentInput],
        [TournamentView],
        [],
      ),
    'editPlayer' : IDL.Func([EditPlayerInput], [], []),
    'generateFixtures' : IDL.Func([TournamentId], [IDL.Vec(MatchView)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKnockoutBracket' : IDL.Func(
        [TournamentId],
        [IDL.Vec(KnockoutBracketMatch)],
        ['query'],
      ),
    'getLeagueStandings' : IDL.Func(
        [TournamentId],
        [IDL.Vec(LeagueStandingRow)],
        ['query'],
      ),
    'getMatchesByTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(MatchView)],
        ['query'],
      ),
    'getPlayersByTeam' : IDL.Func([TeamId], [IDL.Vec(PlayerView)], ['query']),
    'getPlayersByTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(PlayerView)],
        ['query'],
      ),
    'getRecentResults' : IDL.Func(
        [TournamentId, IDL.Nat],
        [IDL.Vec(MatchView)],
        ['query'],
      ),
    'getTeamsByTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(TeamView)],
        ['query'],
      ),
    'getTournament' : IDL.Func(
        [TournamentId],
        [IDL.Opt(TournamentView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTournaments' : IDL.Func([], [IDL.Vec(TournamentView)], ['query']),
    'updateScore' : IDL.Func([UpdateScoreInput], [], []),
    'updateTournamentStatus' : IDL.Func(
        [TournamentId, TournamentStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };