/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddPlayerInput {
  'name' : string,
  'number' : bigint,
  'teamId' : TeamId,
  'position' : string,
  'tournamentId' : TournamentId,
}
export interface AddTeamInput {
  'name' : string,
  'color' : string,
  'tournamentId' : TournamentId,
}
export interface CreateTournamentInput {
  'totalTeams' : bigint,
  'name' : string,
  'format' : TournamentFormat,
}
export interface EditPlayerInput {
  'playerId' : PlayerId,
  'name' : string,
  'number' : bigint,
  'position' : string,
}
export interface KnockoutBracketMatch {
  'winnerId' : [] | [TeamId],
  'awayTeamId' : [] | [TeamId],
  'homeTeamId' : [] | [TeamId],
  'matchId' : [] | [MatchId],
  'round' : bigint,
}
export interface LeagueStandingRow {
  'won' : bigint,
  'teamName' : string,
  'goalDifference' : bigint,
  'played' : bigint,
  'lost' : bigint,
  'goalsFor' : bigint,
  'goalsAgainst' : bigint,
  'teamId' : TeamId,
  'position' : bigint,
  'drawn' : bigint,
  'points' : bigint,
}
export type MatchId = bigint;
export type MatchPhase = { 'knockoutRound' : bigint } |
  { 'leagueStage' : null };
export type MatchStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface MatchView {
  'id' : MatchId,
  'status' : MatchStatus,
  'completedAt' : [] | [Timestamp],
  'awayTeamId' : TeamId,
  'homeTeamId' : TeamId,
  'homeScore' : bigint,
  'awayScore' : bigint,
  'phase' : MatchPhase,
  'tournamentId' : TournamentId,
  'scheduledAt' : Timestamp,
}
export type PlayerId = bigint;
export interface PlayerView {
  'id' : PlayerId,
  'name' : string,
  'number' : bigint,
  'teamId' : TeamId,
  'position' : string,
  'tournamentId' : TournamentId,
}
export type TeamId = bigint;
export interface TeamView {
  'id' : TeamId,
  'name' : string,
  'color' : string,
  'tournamentId' : TournamentId,
}
export type Timestamp = bigint;
export type TournamentFormat = { 'knockout' : null } |
  { 'hybrid' : null } |
  { 'league' : null };
export type TournamentId = bigint;
export type TournamentStatus = { 'active' : null } |
  { 'upcoming' : null } |
  { 'completed' : null };
export interface TournamentView {
  'id' : TournamentId,
  'status' : TournamentStatus,
  'totalTeams' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'format' : TournamentFormat,
}
export interface UpdateScoreInput {
  'matchId' : MatchId,
  'homeScore' : bigint,
  'awayScore' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPlayer' : ActorMethod<[AddPlayerInput], PlayerView>,
  'addTeam' : ActorMethod<[AddTeamInput], TeamView>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeMatch' : ActorMethod<[MatchId], undefined>,
  'createTournament' : ActorMethod<[CreateTournamentInput], TournamentView>,
  'editPlayer' : ActorMethod<[EditPlayerInput], undefined>,
  'generateFixtures' : ActorMethod<[TournamentId], Array<MatchView>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKnockoutBracket' : ActorMethod<
    [TournamentId],
    Array<KnockoutBracketMatch>
  >,
  'getLeagueStandings' : ActorMethod<[TournamentId], Array<LeagueStandingRow>>,
  'getMatchesByTournament' : ActorMethod<[TournamentId], Array<MatchView>>,
  'getPlayersByTeam' : ActorMethod<[TeamId], Array<PlayerView>>,
  'getPlayersByTournament' : ActorMethod<[TournamentId], Array<PlayerView>>,
  'getRecentResults' : ActorMethod<[TournamentId, bigint], Array<MatchView>>,
  'getTeamsByTournament' : ActorMethod<[TournamentId], Array<TeamView>>,
  'getTournament' : ActorMethod<[TournamentId], [] | [TournamentView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTournaments' : ActorMethod<[], Array<TournamentView>>,
  'updateScore' : ActorMethod<[UpdateScoreInput], undefined>,
  'updateTournamentStatus' : ActorMethod<
    [TournamentId, TournamentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];