/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddTeamInput {
    name: string;
    color: string;
    tournamentId: TournamentId;
}
export type Timestamp = bigint;
export interface TournamentView {
    id: TournamentId;
    status: TournamentStatus;
    totalTeams: bigint;
    name: string;
    createdAt: Timestamp;
    format: TournamentFormat;
}
export interface TeamView {
    id: TeamId;
    name: string;
    color: string;
    tournamentId: TournamentId;
}
export type MatchPhase = {
    __kind__: "knockoutRound";
    knockoutRound: bigint;
} | {
    __kind__: "leagueStage";
    leagueStage: null;
};
export interface EditPlayerInput {
    playerId: PlayerId;
    name: string;
    number: bigint;
    position: string;
}
export interface MatchView {
    id: MatchId;
    status: MatchStatus;
    completedAt?: Timestamp;
    awayTeamId: TeamId;
    homeTeamId: TeamId;
    homeScore: bigint;
    awayScore: bigint;
    phase: MatchPhase;
    tournamentId: TournamentId;
    scheduledAt: Timestamp;
}
export type MatchId = bigint;
export type TeamId = bigint;
export type PlayerId = bigint;
export type TournamentId = bigint;
export interface LeagueStandingRow {
    won: bigint;
    teamName: string;
    goalDifference: bigint;
    played: bigint;
    lost: bigint;
    goalsFor: bigint;
    goalsAgainst: bigint;
    teamId: TeamId;
    position: bigint;
    drawn: bigint;
    points: bigint;
}
export interface CreateTournamentInput {
    totalTeams: bigint;
    name: string;
    format: TournamentFormat;
}
export interface AddPlayerInput {
    name: string;
    number: bigint;
    teamId: TeamId;
    position: string;
    tournamentId: TournamentId;
}
export interface UpdateScoreInput {
    matchId: MatchId;
    homeScore: bigint;
    awayScore: bigint;
}
export interface KnockoutBracketMatch {
    winnerId?: TeamId;
    awayTeamId?: TeamId;
    homeTeamId?: TeamId;
    matchId?: MatchId;
    round: bigint;
}
export interface PlayerView {
    id: PlayerId;
    name: string;
    number: bigint;
    teamId: TeamId;
    position: string;
    tournamentId: TournamentId;
}
export enum MatchStatus {
    scheduled = "scheduled",
    live = "live",
    completed = "completed"
}
export enum TournamentFormat {
    knockout = "knockout",
    hybrid = "hybrid",
    league = "league"
}
export enum TournamentStatus {
    active = "active",
    upcoming = "upcoming",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addPlayer(input: AddPlayerInput): Promise<PlayerView>;
    addTeam(input: AddTeamInput): Promise<TeamView>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeMatch(matchId: MatchId): Promise<void>;
    createTournament(input: CreateTournamentInput): Promise<TournamentView>;
    editPlayer(input: EditPlayerInput): Promise<void>;
    generateFixtures(tournamentId: TournamentId): Promise<Array<MatchView>>;
    getCallerUserRole(): Promise<UserRole>;
    getKnockoutBracket(tournamentId: TournamentId): Promise<Array<KnockoutBracketMatch>>;
    getLeagueStandings(tournamentId: TournamentId): Promise<Array<LeagueStandingRow>>;
    getMatchesByTournament(tournamentId: TournamentId): Promise<Array<MatchView>>;
    getPlayersByTeam(teamId: TeamId): Promise<Array<PlayerView>>;
    getPlayersByTournament(tournamentId: TournamentId): Promise<Array<PlayerView>>;
    getRecentResults(tournamentId: TournamentId, limit: bigint): Promise<Array<MatchView>>;
    getTeamsByTournament(tournamentId: TournamentId): Promise<Array<TeamView>>;
    getTournament(tournamentId: TournamentId): Promise<TournamentView | null>;
    isCallerAdmin(): Promise<boolean>;
    listTournaments(): Promise<Array<TournamentView>>;
    updateScore(input: UpdateScoreInput): Promise<void>;
    updateTournamentStatus(tournamentId: TournamentId, status: TournamentStatus): Promise<void>;
}
import type { CreateTournamentInput as _CreateTournamentInput, KnockoutBracketMatch as _KnockoutBracketMatch, MatchId as _MatchId, MatchPhase as _MatchPhase, MatchStatus as _MatchStatus, MatchView as _MatchView, TeamId as _TeamId, Timestamp as _Timestamp, TournamentFormat as _TournamentFormat, TournamentId as _TournamentId, TournamentStatus as _TournamentStatus, TournamentView as _TournamentView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addPlayer(arg0: AddPlayerInput): Promise<PlayerView> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0);
            return result;
        }
    }
    async addTeam(arg0: AddTeamInput): Promise<TeamView> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeMatch(arg0: MatchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMatch(arg0);
            return result;
        }
    }
    async createTournament(arg0: CreateTournamentInput): Promise<TournamentView> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(to_candid_CreateTournamentInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TournamentView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(to_candid_CreateTournamentInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TournamentView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async editPlayer(arg0: EditPlayerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPlayer(arg0);
            return result;
        }
    }
    async generateFixtures(arg0: TournamentId): Promise<Array<MatchView>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateFixtures(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateFixtures(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKnockoutBracket(arg0: TournamentId): Promise<Array<KnockoutBracketMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnockoutBracket(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnockoutBracket(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeagueStandings(arg0: TournamentId): Promise<Array<LeagueStandingRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeagueStandings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeagueStandings(arg0);
            return result;
        }
    }
    async getMatchesByTournament(arg0: TournamentId): Promise<Array<MatchView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesByTournament(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesByTournament(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTeam(arg0: TeamId): Promise<Array<PlayerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTeam(arg0);
            return result;
        }
    }
    async getPlayersByTournament(arg0: TournamentId): Promise<Array<PlayerView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTournament(arg0);
            return result;
        }
    }
    async getRecentResults(arg0: TournamentId, arg1: bigint): Promise<Array<MatchView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentResults(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentResults(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamsByTournament(arg0: TournamentId): Promise<Array<TeamView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamsByTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamsByTournament(arg0);
            return result;
        }
    }
    async getTournament(arg0: TournamentId): Promise<TournamentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTournaments(): Promise<Array<TournamentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTournaments();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTournaments();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateScore(arg0: UpdateScoreInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScore(arg0);
            return result;
        }
    }
    async updateTournamentStatus(arg0: TournamentId, arg1: TournamentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_KnockoutBracketMatch_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnockoutBracketMatch): KnockoutBracketMatch {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MatchPhase_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchPhase): MatchPhase {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MatchView_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchView): MatchView {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentFormat_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentFormat): TournamentFormat {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentView): TournamentView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamId]): TeamId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchId]): MatchId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentView]): TournamentView | null {
    return value.length === 0 ? null : from_candid_TournamentView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    status: _MatchStatus;
    completedAt: [] | [_Timestamp];
    awayTeamId: _TeamId;
    homeTeamId: _TeamId;
    homeScore: bigint;
    awayScore: bigint;
    phase: _MatchPhase;
    tournamentId: _TournamentId;
    scheduledAt: _Timestamp;
}): {
    id: MatchId;
    status: MatchStatus;
    completedAt?: Timestamp;
    awayTeamId: TeamId;
    homeTeamId: TeamId;
    homeScore: bigint;
    awayScore: bigint;
    phase: MatchPhase;
    tournamentId: TournamentId;
    scheduledAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n16(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.completedAt)),
        awayTeamId: value.awayTeamId,
        homeTeamId: value.homeTeamId,
        homeScore: value.homeScore,
        awayScore: value.awayScore,
        phase: from_candid_MatchPhase_n19(_uploadFile, _downloadFile, value.phase),
        tournamentId: value.tournamentId,
        scheduledAt: value.scheduledAt
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    winnerId: [] | [_TeamId];
    awayTeamId: [] | [_TeamId];
    homeTeamId: [] | [_TeamId];
    matchId: [] | [_MatchId];
    round: bigint;
}): {
    winnerId?: TeamId;
    awayTeamId?: TeamId;
    homeTeamId?: TeamId;
    matchId?: MatchId;
    round: bigint;
} {
    return {
        winnerId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.winnerId)),
        awayTeamId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.awayTeamId)),
        homeTeamId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.homeTeamId)),
        matchId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.matchId)),
        round: value.round
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TournamentId;
    status: _TournamentStatus;
    totalTeams: bigint;
    name: string;
    createdAt: _Timestamp;
    format: _TournamentFormat;
}): {
    id: TournamentId;
    status: TournamentStatus;
    totalTeams: bigint;
    name: string;
    createdAt: Timestamp;
    format: TournamentFormat;
} {
    return {
        id: value.id,
        status: from_candid_TournamentStatus_n9(_uploadFile, _downloadFile, value.status),
        totalTeams: value.totalTeams,
        name: value.name,
        createdAt: value.createdAt,
        format: from_candid_TournamentFormat_n11(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    upcoming: null;
} | {
    completed: null;
}): TournamentStatus {
    return "active" in value ? TournamentStatus.active : "upcoming" in value ? TournamentStatus.upcoming : "completed" in value ? TournamentStatus.completed : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    knockout: null;
} | {
    hybrid: null;
} | {
    league: null;
}): TournamentFormat {
    return "knockout" in value ? TournamentFormat.knockout : "hybrid" in value ? TournamentFormat.hybrid : "league" in value ? TournamentFormat.league : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    knockoutRound: bigint;
} | {
    leagueStage: null;
}): {
    __kind__: "knockoutRound";
    knockoutRound: bigint;
} | {
    __kind__: "leagueStage";
    leagueStage: null;
} {
    return "knockoutRound" in value ? {
        __kind__: "knockoutRound",
        knockoutRound: value.knockoutRound
    } : "leagueStage" in value ? {
        __kind__: "leagueStage",
        leagueStage: value.leagueStage
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchView>): Array<MatchView> {
    return value.map((x)=>from_candid_MatchView_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KnockoutBracketMatch>): Array<KnockoutBracketMatch> {
    return value.map((x)=>from_candid_KnockoutBracketMatch_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentView>): Array<TournamentView> {
    return value.map((x)=>from_candid_TournamentView_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CreateTournamentInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTournamentInput): _CreateTournamentInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentFormat_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentFormat): _TournamentFormat {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTeams: bigint;
    name: string;
    format: TournamentFormat;
}): {
    totalTeams: bigint;
    name: string;
    format: _TournamentFormat;
} {
    return {
        totalTeams: value.totalTeams,
        name: value.name,
        format: to_candid_TournamentFormat_n5(_uploadFile, _downloadFile, value.format)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    active: null;
} | {
    upcoming: null;
} | {
    completed: null;
} {
    return value == TournamentStatus.active ? {
        active: null
    } : value == TournamentStatus.upcoming ? {
        upcoming: null
    } : value == TournamentStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentFormat): {
    knockout: null;
} | {
    hybrid: null;
} | {
    league: null;
} {
    return value == TournamentFormat.knockout ? {
        knockout: null
    } : value == TournamentFormat.hybrid ? {
        hybrid: null
    } : value == TournamentFormat.league ? {
        league: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
